defaults:
  - _self_
  - override hydra/launcher: submitit_slurm

project: clip_field
deterministic_id: false
device: cuda
use_cache: false
batch_size: 12544

# Dataset details
dataset_path: ../CDSLab.r3d
use_cache_dataset: false
cache_result: true
cache_path: detic_labeled_dataset_gpt_100_test_labels.pt
saved_dataset_path: detic_labeled_dataset_gpt_100_test_labels.pt

# Data loading and labelling specs
sample_freq: 5
threshold: 0.4
subsample_prob: 0.01
use_lseg: false
use_extra_classes: false
use_gt_classes_in_detic: true

# Neural field specs
model_type: hash
num_grid_levels: 18
level_dim: 8  # So total dimension 144
per_level_scale: 2
mlp_depth: 1
mlp_width: 600
log2_hashmap_size: 20

# Training specs
seed: 42
epochs: 80
exp_decay_coeff: 0.5
image_to_label_loss_ratio: 1.0
label_to_image_loss_ratio: 1.0
instance_loss_scale: 100.0
epoch_size: 3e6
dataparallel: false
num_workers: 10

# Debug purposes, visualize Detic results
visualize_detic_results: true
detic_visualization_path: "detic_debug"

# Cache only runs are for building per-dataset caches, which can be used for multi-run later.
cache_only_run: false

# Learning rate data
lr: 1e-4
weight_decay: 0.003
betas:
  - 0.9
  - 0.999
  
# Scheduler data
step_size: 20
gamma: 0.5

save_directory: "kitchen_gpt_100_test_labels"

web_models:
  segmentation: "owl"
  #clip: "ViT-B/32"
  clip: "google/owlvit-base-patch32"
  sentence: "all-mpnet-base-v2"

hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback

  launcher:
    timeout_min: 180
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 128
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    signal_delay_s: 120
    max_num_timeout: 1
    additional_parameters: {}
    array_parallelism: 256
    setup: null
    partition: learnfair

# Add any custom labels you want here
custom_labels:
  - cube
  - bottle
  - mustard
  - trash can
  - package
  - puppy recipe
  - USB connector
  - plants
  - marker pen
  - scissors
  - paper towels
  - tomato soup can
  - ca
  - apple
  - mountain dew
  - ping pong ball
  - lego
  - cup
  - duck
  # We do not want to miss zero point in our point cloud
  - tape
  - green tape
  - green tape on the ground
  - tape on the ground
  - tape on the floor
  - toy brick
  - disinfecting wipes

# Or just comment it out for SCANNET 200 labels.
#custom_labels: null
